In [1]:
spark

In [2]:
from pyspark.sql import SparkSession
from pyspark.sql.functions import col,sum, isnan, when, count,to_timestamp,datediff,sum as _sum,to_date, year, month, dayofmonth
spark = SparkSession.builder.getOrCreate()

In [23]:
# df0 = spark.read.csv("hdfs://namenode:8020/user/root/ecommerce/customers/", header=True, inferSchema=True)
# df1 = spark.read.csv("hdfs://namenode:8020/user/root/ecommerce/orders/", header=True, inferSchema=True)
# df2 = spark.read.csv("hdfs://namenode:8020/user/root/ecommerce/order_items/", header=True, inferSchema=True)
# df3 = spark.read.csv("hdfs://namenode:8020/user/root/ecommerce/reviews/", header=True, inferSchema=True)
# df4 = spark.read.csv("hdfs://namenode:8020/user/root/ecommerce/products/", header=True, inferSchema=True)

In [24]:
# df0.write.mode("overwrite").parquet("hdfs://namenode:8020/user/root/ecommerce_parquet/customers/")
# df1.write.mode("overwrite").parquet("hdfs://namenode:8020/user/root/ecommerce_parquet/orders/")
# df2.write.mode("overwrite").parquet("hdfs://namenode:8020/user/root/ecommerce_parquet/order_items/")
# df3.write.mode("overwrite").parquet("hdfs://namenode:8020/user/root/ecommerce_parquet/reviews/")
# df4.write.mode("overwrite").parquet("hdfs://namenode:8020/user/root/ecommerce_parquet/products/")

In [2]:
df0 = spark.read.parquet("hdfs://namenode:8020/user/root/ecommerce_parquet/customers/")
df1 = spark.read.parquet("hdfs://namenode:8020/user/root/ecommerce_parquet/orders/")
df2 = spark.read.parquet("hdfs://namenode:8020/user/root/ecommerce_parquet/order_items/")
df3 = spark.read.parquet("hdfs://namenode:8020/user/root/ecommerce_parquet/reviews/")
df4 = spark.read.parquet("hdfs://namenode:8020/user/root/ecommerce_parquet/products/")

In [3]:
def get_printSchema(df,name):
    print(f" in the {name} table ")
    df.printSchema()

In [72]:
get_printSchema(df0,"customers")
get_printSchema(df1,"orders")
get_printSchema(df2,"order_items")
get_printSchema(df3,"reviews")
get_printSchema(df4, "products")

 in the customers table
root
 |-- customer_id: string (nullable = true)
 |-- customer_unique_id: string (nullable = true)
 |-- customer_zip_code_prefix: integer (nullable = true)
 |-- customer_city: string (nullable = true)
 |-- customer_state: string (nullable = true)

 in the orders table
root
 |-- order_id: string (nullable = true)
 |-- customer_id: string (nullable = true)
 |-- order_status: string (nullable = true)
 |-- order_purchase_timestamp: timestamp (nullable = true)
 |-- order_approved_at: timestamp (nullable = true)
 |-- order_delivered_carrier_date: timestamp (nullable = true)
 |-- order_delivered_customer_date: timestamp (nullable = true)
 |-- order_estimated_delivery_date: timestamp (nullable = true)

 in the order_items table
root
 |-- order_id: string (nullable = true)
 |-- order_item_id: integer (nullable = true)
 |-- product_id: string (nullable = true)
 |-- seller_id: string (nullable = true)
 |-- shipping_limit_date: timestamp (nullable = true)
 |-- price: double (nullable = true)
 |-- freight_value: double (nullable = true)

 in the reviews table
root
 |-- review_id: string (nullable = true)
 |-- order_id: string (nullable = true)
 |-- review_score: string (nullable = true)
 |-- review_comment_title: string (nullable = true)
 |-- review_comment_message: string (nullable = true)
 |-- review_creation_date: string (nullable = true)
 |-- review_answer_timestamp: string (nullable = true)

 in the products table
root
 |-- product_id: string (nullable = true)
 |-- product_category_name: string (nullable = true)
 |-- product_name_lenght: integer (nullable = true)
 |-- product_description_lenght: integer (nullable = true)
 |-- product_photos_qty: integer (nullable = true)
 |-- product_weight_g: integer (nullable = true)
 |-- product_length_cm: integer (nullable = true)
 |-- product_height_cm: integer (nullable = true)
 |-- product_width_cm: integer (nullable = true)

# Fix reviews table

In [83]:
df3= df3.withColumn("review_score",col("review_score").cast("int"))\
    .withColumn("review_creation_date", to_timestamp("review_creation_date")) \
    .withColumn("review_answer_timestamp", to_timestamp("review_answer_timestamp")) \

In [98]:
df4.toPandas()

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
0,1e9e8ef04dbcff4541ed26657ea517e5,perfumaria,40.0,287.0,1.0,225.0,16.0,10.0,14.0
1,3aa071139cb16b67ca9e5dea641aaa2f,artes,44.0,276.0,1.0,1000.0,30.0,18.0,20.0
2,96bd76ec8810374ed1b65e291975717f,esporte_lazer,46.0,250.0,1.0,154.0,18.0,9.0,15.0
3,cef67bcfe19066a932b7673e239eb23d,bebes,27.0,261.0,1.0,371.0,26.0,4.0,26.0
4,9dc1a7de274444849c219cff195d0b71,utilidades_domesticas,37.0,402.0,4.0,625.0,20.0,17.0,13.0
...,...,...,...,...,...,...,...,...,...
32946,a0b7d5a992ccda646f2d34e418fff5a0,moveis_decoracao,45.0,67.0,2.0,12300.0,40.0,40.0,40.0
32947,bf4538d88321d0fd4412a93c974510e6,construcao_ferramentas_iluminacao,41.0,971.0,1.0,1700.0,16.0,19.0,16.0
32948,9a7c6041fa9592d9d9ef6cfe62a71f8c,cama_mesa_banho,50.0,799.0,1.0,1400.0,27.0,7.0,27.0
32949,83808703fc0706a22e264b9d75f04a2e,informatica_acessorios,60.0,156.0,2.0,700.0,31.0,13.0,20.0
32950,106392145fca363410d287a815be6de4,cama_mesa_banho,58.0,309.0,1.0,2083.0,12.0,2.0,7.0

In [24]:
def get_describe(df,name):
    print(f"Describe for {name} table") 
    df.describe().show(vertical=True)

In [25]:
get_describe(df0, "customers")
get_describe(df1,"orders")
get_describe(df2,"order_items")
get_describe(df3, "reviews")
get_describe(df4, "products")

Describe for customers table
-RECORD 0----------------------------------------
 summary                  | count
 customer_id              | 99441
 customer_unique_id       | 99441
 customer_zip_code_prefix | 99441
 customer_city            | 99441
 customer_state           | 99441
-RECORD 1----------------------------------------
 summary                  | mean
 customer_id              | null
 customer_unique_id       | null
 customer_zip_code_prefix | 35137.47458291851
 customer_city            | null
 customer_state           | null
-RECORD 2----------------------------------------
 summary                  | stddev
 customer_id              | null
 customer_unique_id       | null
 customer_zip_code_prefix | 29797.93899620613
 customer_city            | null
 customer_state           | null
-RECORD 3----------------------------------------
 summary                  | min
 customer_id              | 00012a2ce6f8dcda2...
 customer_unique_id       | 0000366f3b9a7992b...
 customer_zip_code_prefix | 1003
 customer_city            | abadia dos dourados
 customer_state           | AC
-RECORD 4----------------------------------------
 summary                  | max
 customer_id              | ffffe8b65bbe3087b...
 customer_unique_id       | ffffd2657e2aad290...
 customer_zip_code_prefix | 99990
 customer_city            | zortea
 customer_state           | TO

Describe for orders table
-RECORD 0----------------------------
 summary      | count
 order_id     | 99441
 customer_id  | 99441
 order_status | 99441
-RECORD 1----------------------------
 summary      | mean
 order_id     | null
 customer_id  | null
 order_status | null
-RECORD 2----------------------------
 summary      | stddev
 order_id     | null
 customer_id  | null
 order_status | null
-RECORD 3----------------------------
 summary      | min
 order_id     | 00010242fe8c5a6d1...
 customer_id  | 00012a2ce6f8dcda2...
 order_status | approved
-RECORD 4----------------------------
 summary      | max
 order_id     | fffe41c64501cc87c...
 customer_id  | ffffe8b65bbe3087b...
 order_status | unavailable

Describe for order_items table
-RECORD 0-----------------------------
 summary       | count
 order_id      | 112650
 order_item_id | 112650
 product_id    | 112650
 seller_id     | 112650
 price         | 112650
 freight_value | 112650
-RECORD 1-----------------------------
 summary       | mean
 order_id      | null
 order_item_id | 1.1978339991122948
 product_id    | null
 seller_id     | null
 price         | 120.65373901464174
 freight_value | 19.990319928982977
-RECORD 2-----------------------------
 summary       | stddev
 order_id      | null
 order_item_id | 0.7051240313951721
 product_id    | null
 seller_id     | null
 price         | 183.6339280502595
 freight_value | 15.806405412297098
-RECORD 3-----------------------------
 summary       | min
 order_id      | 00010242fe8c5a6d1...
 order_item_id | 1
 product_id    | 00066f42aeeb9f300...
 seller_id     | 0015a82c2db000af6...
 price         | 0.85
 freight_value | 0.0
-RECORD 4-----------------------------
 summary       | max
 order_id      | fffe41c64501cc87c...
 order_item_id | 21
 product_id    | fffe9eeff12fcbd74...
 seller_id     | ffff564a4f9085cd2...
 price         | 6735.0
 freight_value | 409.68

Describe for reviews table
-RECORD 0---------------------------------------
 summary                 | count
 review_id               | 104161
 order_id                | 101926
 review_score            | 101782
 review_comment_title    | 12005
 review_comment_message  | 41083
 review_creation_date    | 95398
 review_answer_timestamp | 95377
-RECORD 1---------------------------------------
 summary                 | mean
 review_id               | 4.5
 order_id                | 0.0
 review_score            | 4.087204087597126
 review_comment_title    | 3.165434995880696E10
 review_comment_message  | 8.172413793103448
 review_creation_date    | null
 review_answer_timestamp | null
-RECORD 2---------------------------------------
 summary                 | stddev
 review_id               | 0.7071067811865476
 order_id                | 0.0
 review_score            | 1.3750046423971858
 review_comment_title    | 5.625434750908947E11
 review_comment_message  | 3.1175650470615843
 review_creation_date    | null
 review_answer_timestamp | null
-RECORD 3---------------------------------------
 summary                 | min
 review_id               |  "
 order_id                |
 review_score            |  "
 review_comment_title    |
 review_comment_message  |
 review_creation_date    |  FOI A MINHA PRIM...
 review_answer_timestamp |  POIS NÃO CUMPREM...
-RECORD 4---------------------------------------
 summary                 | max
 review_id               | 🤙🏼👏🏼👏🏼"
 order_id                | visando sempre o ...
 review_score            | seria mais coeren...
 review_comment_title    | 🔟
 review_comment_message  | 😡😡😡😡😡👎👎👎👎👎
 review_creation_date    | veio bem embalada...
 review_answer_timestamp | 70 + R$15

Describe for products table
-RECORD 0------------------------------------------
 summary                    | count
 product_id                 | 32951
 product_category_name      | 32341
 product_name_lenght        | 32341
 product_description_lenght | 32341
 product_photos_qty         | 32341
 product_weight_g           | 32949
 product_length_cm          | 32949
 product_height_cm          | 32949
 product_width_cm           | 32949
-RECORD 1------------------------------------------
 summary                    | mean
 product_id                 | null
 product_category_name      | null
 product_name_lenght        | 48.47694876472589
 product_description_lenght | 771.4952846232337
 product_photos_qty         | 2.1889861166939797
 product_weight_g           | 2276.4724877841513
 product_length_cm          | 30.81507784758263
 product_height_cm          | 16.937661234028347
 product_width_cm           | 23.196728277034204
-RECORD 2------------------------------------------
 summary                    | stddev
 product_id                 | null
 product_category_name      | null
 product_name_lenght        | 10.245740725237287
 product_description_lenght | 635.1152246349538
 product_photos_qty         | 1.7367656379315435
 product_weight_g           | 4282.038730977024
 product_length_cm          | 16.914458054065953
 product_height_cm          | 13.637554061749569
 product_width_cm           | 12.079047453227794
-RECORD 3------------------------------------------
 summary                    | min
 product_id                 | 00066f42aeeb9f300...
 product_category_name      | agro_industria_e_...
 product_name_lenght        | 5
 product_description_lenght | 4
 product_photos_qty         | 1
 product_weight_g           | 0
 product_length_cm          | 7
 product_height_cm          | 2
 product_width_cm           | 6
-RECORD 4------------------------------------------
 summary                    | max
 product_id                 | fffe9eeff12fcbd74...
 product_category_name      | utilidades_domest...
 product_name_lenght        | 76
 product_description_lenght | 3992
 product_photos_qty         | 20
 product_weight_g           | 40425
 product_length_cm          | 105
 product_height_cm          | 105
 product_width_cm           | 118

## Check Duplicates (just keys)

In [7]:
customers_dup = df0.groupBy("customer_id").count().filter("count > 1")

In [8]:
customers_dup.show()

+-----------+-----+
|customer_id|count|
+-----------+-----+
+-----------+-----+

In [9]:
orders_dup = df1.groupBy("order_id") \
    .count() \
    .filter("count > 1")

orders_dup.show()

+--------+-----+
|order_id|count|
+--------+-----+
+--------+-----+

In [10]:
order_items_dup = df2.groupBy("order_id", "order_item_id") \
    .count() \
    .filter("count > 1")

order_items_dup.show()

+--------+-------------+-----+
|order_id|order_item_id|count|
+--------+-------------+-----+
+--------+-------------+-----+

In [11]:
reviews_dup = df3.groupBy("review_id") \
    .count() \
    .filter("count > 1")

reviews_dup.show()

+--------------------+-----+
|           review_id|count|
+--------------------+-----+
|f144ac19984746532...|    2|
|e4f5fbbbf2fa8f259...|    2|
|868c4827b9ab72723...|    2|
|a8ffb30c74397c7cf...|    2|
|f6e05a3f6dbc3bdb1...|    2|
|c9a406d3076559e35...|    2|
|95cfb15ad3477fec5...|    2|
|dbcd301b59c7e85e6...|    2|
|,2017-08-10 00:00...|    2|
|dd43a798c9e8baf7b...|    2|
|9a07cb8136a1792e7...|    2|
|ef60daa08e71f279b...|    2|
|4812973f7fb59a488...|    2|
|f45e3373e177f5694...|    2|
|9d7b240dff5539983...|    2|
|c1dd7c6a2154caaf1...|    2|
|bee3c76b6017ec9de...|    2|
|1961cafe1d1cbd4cc...|    2|
|4e9a141db068cf685...|    2|
|TEM COMO VCS VERI...|    2|
+--------------------+-----+
only showing top 20 rows

In [12]:
products_dup = df4.groupBy("product_id") \
    .count() \
    .filter("count > 1")

products_dup.show()

+----------+-----+
|product_id|count|
+----------+-----+
+----------+-----+

## Get ALL duplicates summary

In [13]:
def find_duplicates(df,keys,name):
    
    print(f"Checking duplicates for {name}")
    dub=df.groupBy(keys) \
        .count() \
        .filter("count > 1")
    dub.show()

In [14]:
find_duplicates(df0, ["customer_id"], "customers")
find_duplicates(df1, ["order_id"], "orders")
find_duplicates(df2, ["order_id", "order_item_id"], "order_items")
find_duplicates(df3, ["review_id"], "reviews")
find_duplicates(df4, ["product_id"], "products")

Checking duplicates for customers
+-----------+-----+
|customer_id|count|
+-----------+-----+
+-----------+-----+

Checking duplicates for orders
+--------+-----+
|order_id|count|
+--------+-----+
+--------+-----+

Checking duplicates for order_items
+--------+-------------+-----+
|order_id|order_item_id|count|
+--------+-------------+-----+
+--------+-------------+-----+

Checking duplicates for reviews
+--------------------+-----+
|           review_id|count|
+--------------------+-----+
|f144ac19984746532...|    2|
|e4f5fbbbf2fa8f259...|    2|
|868c4827b9ab72723...|    2|
|a8ffb30c74397c7cf...|    2|
|f6e05a3f6dbc3bdb1...|    2|
|c9a406d3076559e35...|    2|
|95cfb15ad3477fec5...|    2|
|dbcd301b59c7e85e6...|    2|
|,2017-08-10 00:00...|    2|
|dd43a798c9e8baf7b...|    2|
|9a07cb8136a1792e7...|    2|
|ef60daa08e71f279b...|    2|
|4812973f7fb59a488...|    2|
|f45e3373e177f5694...|    2|
|9d7b240dff5539983...|    2|
|c1dd7c6a2154caaf1...|    2|
|bee3c76b6017ec9de...|    2|
|1961cafe1d1cbd4cc...|    2|
|4e9a141db068cf685...|    2|
|TEM COMO VCS VERI...|    2|
+--------------------+-----+
only showing top 20 rows

Checking duplicates for products
+----------+-----+
|product_id|count|
+----------+-----+
+----------+-----+

## From the prevouse table reviews conatin dublicate

## check_dublicate_rows_(not just keys)

In [32]:
df3.filter(
    df3.review_id.isin(
        df3.groupBy("review_id")
        .count()
        .filter("count > 1")
        .select("review_id")
        .rdd.flatMap(lambda x: x)
        .collect()
    )
).show(3)

+--------------------+--------------------+-------------------+--------------------+----------------------+--------------------+-----------------------+
|           review_id|            order_id|       review_score|review_comment_title|review_comment_message|review_creation_date|review_answer_timestamp|
+--------------------+--------------------+-------------------+--------------------+----------------------+--------------------+-----------------------+
|           Parabéns"| 2017-08-29 00:00:00|2017-08-29 21:06:01|                null|                  null|                null|                   null|
|                  ."| 2018-05-15 00:00:00|2018-05-16 23:41:51|                null|                  null|                null|                   null|
|28642ce6250b94cc7...|e239d280236cdd3c4...|                  5|                null|                  null| 2018-03-25 00:00:00|    2018-03-25 21:03:02|
+--------------------+--------------------+-------------------+--------------------+----------------------+--------------------+-----------------------+
only showing top 3 rows

# Remove duplicates

In [33]:
df3_clean = df3.dropDuplicates(["review_id"])

In [34]:
df3_clean.filter(
    df3_clean.review_id.isin(
        df3_clean.groupBy("review_id")
        .count()
        .filter("count > 1")
        .select("review_id")
        .rdd.flatMap(lambda x: x)
        .collect()
    )
).show(3)

+---------+--------+------------+--------------------+----------------------+--------------------+-----------------------+
|review_id|order_id|review_score|review_comment_title|review_comment_message|review_creation_date|review_answer_timestamp|
+---------+--------+------------+--------------------+----------------------+--------------------+-----------------------+
+---------+--------+------------+--------------------+----------------------+--------------------+-----------------------+

## Check NULL (missing values per column)

In [55]:
def check_null(df,name):
    print(f"Null in the {name} table ")
    df.select([
        sum(col(c).isNull().cast("int")).alias(c)
        for c in df.columns
    ]).show(vertical=True)

In [56]:
check_null(df0, "customers")
check_null(df1, "orders")
check_null(df2,"order_items")
check_null(df3,"reviews")
check_null(df4,"products")

Null in the customers table
-RECORD 0-----------------------
 customer_id              | 0
 customer_unique_id       | 0
 customer_zip_code_prefix | 0
 customer_city            | 0
 customer_state           | 0

Null in the orders table
-RECORD 0-----------------------------
 order_id                      | 0
 customer_id                   | 0
 order_status                  | 0
 order_purchase_timestamp      | 0
 order_approved_at             | 160
 order_delivered_carrier_date  | 1783
 order_delivered_customer_date | 2965
 order_estimated_delivery_date | 0

Null in the order_items table
-RECORD 0------------------
 order_id            | 0
 order_item_id       | 0
 product_id          | 0
 seller_id           | 0
 shipping_limit_date | 0
 price               | 0
 freight_value       | 0

Null in the reviews table
-RECORD 0------------------------
 review_id               | 1
 order_id                | 2236
 review_score            | 2380
 review_comment_title    | 92157
 review_comment_message  | 63079
 review_creation_date    | 8764
 review_answer_timestamp | 8785

Null in the products table
-RECORD 0-------------------------
 product_id                 | 0
 product_category_name      | 610
 product_name_lenght        | 610
 product_description_lenght | 610
 product_photos_qty         | 610
 product_weight_g           | 2
 product_length_cm          | 2
 product_height_cm          | 2
 product_width_cm           | 2

## Check BOTH NULL + NaN

In [63]:
df0.select([
    count(when(col(c).isNull() | isnan(col(c)), c)).alias(c)
    for c in df0.columns
]).show()

+-----------+------------------+------------------------+-------------+--------------+
|customer_id|customer_unique_id|customer_zip_code_prefix|customer_city|customer_state|
+-----------+------------------+------------------------+-------------+--------------+
|          0|                 0|                       0|            0|             0|
+-----------+------------------+------------------------+-------------+--------------+

In [79]:
from pyspark.sql.functions import col, isnan, when, count
from pyspark.sql.types import DoubleType, FloatType

def get_null_nan_counter(df, name):
    print(f"Null/NaN in the {name} table")

    exprs = []
    for field in df.schema.fields:
        col_name = field.name
        col_type = field.dataType

        # Check if numeric
        if isinstance(col_type, (DoubleType, FloatType)):
            expr = count(when(col(col_name).isNull() | isnan(col(col_name)), col_name)).alias(col_name)
        else:
            expr = count(when(col(col_name).isNull(), col_name)).alias(col_name)

        exprs.append(expr)

    df.select(exprs).show(vertical=True)

In [80]:
get_null_nan_counter(df0, "customers")
get_null_nan_counter(df1, "orders")
get_null_nan_counter(df2,"order_items")
get_null_nan_counter(df3,"reviews")
get_null_nan_counter(df4,"products")

Null/NaN in the customers table
-RECORD 0-----------------------
 customer_id              | 0
 customer_unique_id       | 0
 customer_zip_code_prefix | 0
 customer_city            | 0
 customer_state           | 0

Null/NaN in the orders table
-RECORD 0-----------------------------
 order_id                      | 0
 customer_id                   | 0
 order_status                  | 0
 order_purchase_timestamp      | 0
 order_approved_at             | 160
 order_delivered_carrier_date  | 1783
 order_delivered_customer_date | 2965
 order_estimated_delivery_date | 0

Null/NaN in the order_items table
-RECORD 0------------------
 order_id            | 0
 order_item_id       | 0
 product_id          | 0
 seller_id           | 0
 shipping_limit_date | 0
 price               | 0
 freight_value       | 0

Null/NaN in the reviews table
-RECORD 0------------------------
 review_id               | 1
 order_id                | 2236
 review_score            | 2380
 review_comment_title    | 92157
 review_comment_message  | 63079
 review_creation_date    | 8764
 review_answer_timestamp | 8785

Null/NaN in the products table
-RECORD 0-------------------------
 product_id                 | 0
 product_category_name      | 610
 product_name_lenght        | 610
 product_description_lenght | 610
 product_photos_qty         | 610
 product_weight_g           | 2
 product_length_cm          | 2
 product_height_cm          | 2
 product_width_cm           | 2

In [91]:
df2.filter(col("price") < 0).count()

0

# in orders tabls we keep null becouse they repersent real world stated

In [94]:
df3 = df3.dropna(subset=["review_id", "order_id", "review_score"])  ##Drop rows here  :primary key missing,foreign key missing,critical measure missing

In [95]:
df3= df3.fillna({
"review_comment_title": "no title",
    "review_comment_message": "no comment"
})

In [96]:
get_null_nan_counter(df3,"reviews")

Null/NaN in the reviews table
-RECORD 0-----------------------
 review_id               | 0
 order_id                | 0
 review_score            | 0
 review_comment_title    | 0
 review_comment_message  | 0
 review_creation_date    | 3920
 review_answer_timestamp | 3873

### we not address null in review_creation_date,review_answer_timestamp becouse **preserves business reality** event_based

In [97]:
df4 = df4.fillna({
    "product_category_name": "unknown"
})

In [99]:
df4 = df4.fillna({
    "product_name_lenght": 0,
    "product_description_lenght": 0,
    "product_photos_qty": 0,
    "product_weight_g": 0,
    "product_length_cm": 0,
    "product_height_cm": 0,
    "product_width_cm": 0
})

In [104]:
get_null_nan_counter(df0, "customers")
get_null_nan_counter(df1, "orders")
get_null_nan_counter(df2,"order_items")
get_null_nan_counter(df3,"reviews")
get_null_nan_counter(df4,"products")

Null/NaN in the customers table
-RECORD 0-----------------------
 customer_id              | 0
 customer_unique_id       | 0
 customer_zip_code_prefix | 0
 customer_city            | 0
 customer_state           | 0

Null/NaN in the orders table
-RECORD 0-----------------------------
 order_id                      | 0
 customer_id                   | 0
 order_status                  | 0
 order_purchase_timestamp      | 0
 order_approved_at             | 160
 order_delivered_carrier_date  | 1783
 order_delivered_customer_date | 2965
 order_estimated_delivery_date | 0

Null/NaN in the order_items table
-RECORD 0------------------
 order_id            | 0
 order_item_id       | 0
 product_id          | 0
 seller_id           | 0
 shipping_limit_date | 0
 price               | 0
 freight_value       | 0

Null/NaN in the reviews table
-RECORD 0-----------------------
 review_id               | 0
 order_id                | 0
 review_score            | 0
 review_comment_title    | 0
 review_comment_message  | 0
 review_creation_date    | 3920
 review_answer_timestamp | 3873

Null/NaN in the products table
-RECORD 0-------------------------
 product_id                 | 0
 product_category_name      | 0
 product_name_lenght        | 0
 product_description_lenght | 0
 product_photos_qty         | 0
 product_weight_g           | 0
 product_length_cm          | 0
 product_height_cm          | 0
 product_width_cm           | 0

In [108]:
df0.write.mode("overwrite").parquet("hdfs://namenode:8020/user/root/silver/customers/")
df1.write.mode("overwrite").parquet("hdfs://namenode:8020/user/root/silver/orders/")
df2.write.mode("overwrite").parquet("hdfs://namenode:8020/user/root/silver/order_items/")
df3.write.mode("overwrite").parquet("hdfs://namenode:8020/user/root/silver/reviews/")
df4.write.mode("overwrite").parquet("hdfs://namenode:8020/user/root/silver/products/")

## go to see silver_schema_hive_table file

In [ ]:
# you can also create using spark but before enable hive like this when build session  ***.enableHiveSupport()* \
## Spark will: Create schema in Hive Metastore 2-Link table to HDFS path- NOT move or create data
spark.sql("""
create external table silver.silver_customers (  
    product_id STRING,
    product_name STRING,
    price DOUBLE
)
STORED AS PARQUET
LOCATION "hdfs://namenode:8020/user/root/silver/customers/"

""")

In [109]:
# spark.sql("""
# CREATE TABLE products_hive (
#     product_id STRING,
#     product_name STRING,
#     price DOUBLE
# )
# STORED AS PARQUET
# """)


# # and after that you can write 
# ## if i write
# # df.write.mode("overwrite").saveAsTable("users")  store in users/hive /warhouse/users


# saveAsTable()
# Spark decides storage location   , Write data files, Create Hive metadata,Manage storage path
# Usually Hive warehouse directory
# Fully managed by Spark + Hive


# df = spark.sql("SELECT * FROM users")   ## this go to to autmaticaly
# df.show()

+---+---------------+--------------+
| id|           name|       website|
+---+---------------+--------------+
|  1|mahmoud zakaria|www.mahmoud.ma|
+---+---------------+--------------+

## Bronze → Silver (DONE) << Hive_able

In [106]:
df0.show(5)

+--------------------+--------------------+------------------------+--------------------+--------------+
|         customer_id|  customer_unique_id|customer_zip_code_prefix|       customer_city|customer_state|
+--------------------+--------------------+------------------------+--------------------+--------------+
|f2a1d75b74d9ec748...|15ee900ec703c9a10...|                   68590|             jacunda|            PA|
|f15272fe9d0e2ae32...|11e74a9cbe1158d1c...|                   15056|sao jose do rio p...|            SP|
|7324ecb0ff143f561...|c6be127fa6e30c6f7...|                   13302|                 itu|            SP|
|7accf3d920f47c07f...|a7f1a6dc9ba06844b...|                   45638|             coaraci|            BA|
|3680a273ddb333253...|6cbfcc29787035834...|                   29700|            colatina|            ES|
+--------------------+--------------------+------------------------+--------------------+--------------+
only showing top 5 rows

# → Gold (NEXT) → Analytics / BI

In [110]:
## join tables
## create KPIs
## build fact/dimension tables
## prepare data for dashboards (Power BI / Tableau)

In [4]:
customers = spark.read.parquet("hdfs://namenode:8020/user/root/silver/customers/")
orders = spark.read.parquet("hdfs://namenode:8020/user/root/silver/orders/")
order_items = spark.read.parquet("hdfs://namenode:8020/user/root/silver/order_items/")
reviews = spark.read.parquet("hdfs://namenode:8020/user/root/silver/reviews/")
products = spark.read.parquet("hdfs://namenode:8020/user/root/silver/products/")

# Fact Orders Table

In [5]:
orders=orders.withColumn("delivery_time_days",datediff("order_delivered_customer_date", "order_purchase_timestamp")
                          )

# Review analysis

In [6]:
reviews= reviews.withColumn("is_positive",reviews.review_score>=4)

In [7]:
orders.toPandas()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,delivery_time_days
0,995392413cee61cc1fcec9807870ea8c,4bf24904ec428325abad2791fcca1aff,delivered,2017-09-04 22:24:05,2017-09-04 22:43:54,2017-09-13 17:20:04,2017-09-22 21:09:32,2017-09-27,18.0
1,b39de9ed2bb8fd08a970e4517c698824,ed18b557140ff674f36cbcf73921dbbe,delivered,2018-03-27 09:15:17,2018-03-27 09:30:12,2018-03-27 23:52:09,2018-04-11 21:51:02,2018-04-26,15.0
2,b1a88554eb1f7f68627549e26257b583,5cf799d0ac88e1d328434a595c015efa,delivered,2018-06-13 02:19:56,2018-06-14 02:39:10,2018-06-14 13:55:00,2018-06-20 21:07:29,2018-07-13,7.0
3,fe2ac30768e07e362b649951cc625144,be07f06f183227b5c2b31c30fbb4f382,delivered,2017-01-16 16:41:18,2017-01-16 17:30:23,2017-01-17 11:26:52,2017-01-26 16:24:07,2017-02-22,10.0
4,460673777918e7a42a262293341ae7d5,6f352988122e277e645d36a012e66bcb,delivered,2018-02-07 22:38:41,2018-02-08 22:30:24,2018-02-09 16:56:51,2018-02-24 18:06:45,2018-03-05,17.0
...,...,...,...,...,...,...,...,...,...
99436,9c5dedf39a927c1b2549525ed64a053c,39bd1228ee8140590ac3aca26f2dfe00,delivered,2017-03-09 09:54:05,2017-03-09 09:54:05,2017-03-10 11:18:03,2017-03-17 15:08:01,2017-03-28,8.0
99437,63943bddc261676b46f01ca7ac2f7bd8,1fca14ff2861355f6e5f14306ff977a7,delivered,2018-02-06 12:58:58,2018-02-06 13:10:37,2018-02-07 23:22:42,2018-02-28 17:37:56,2018-03-02,22.0
99438,83c1379a015df1e13d02aae0204711ab,1aa71eb042121263aafbe80c1b562c9c,delivered,2017-08-27 14:46:43,2017-08-27 15:04:16,2017-08-28 20:52:26,2017-09-21 11:24:17,2017-09-27,25.0
99439,11c177c8e97725db2631073c19f07b62,b331b74b18dc79bcdf6532d51e1637c1,delivered,2018-01-08 21:28:27,2018-01-08 21:36:21,2018-01-12 15:35:03,2018-01-25 23:32:54,2018-02-15,17.0
99440,66dea50a8b16d9b4dee7af250b4be1a5,edb027a75a1449115f6b43211ae02a24,delivered,2018-03-08 20:57:30,2018-03-09 11:20:28,2018-03-09 22:11:59,2018-03-16 13:08:30,2018-04-03,8.0

In [8]:
orders.toPandas()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,delivery_time_days
0,995392413cee61cc1fcec9807870ea8c,4bf24904ec428325abad2791fcca1aff,delivered,2017-09-04 22:24:05,2017-09-04 22:43:54,2017-09-13 17:20:04,2017-09-22 21:09:32,2017-09-27,18.0
1,b39de9ed2bb8fd08a970e4517c698824,ed18b557140ff674f36cbcf73921dbbe,delivered,2018-03-27 09:15:17,2018-03-27 09:30:12,2018-03-27 23:52:09,2018-04-11 21:51:02,2018-04-26,15.0
2,b1a88554eb1f7f68627549e26257b583,5cf799d0ac88e1d328434a595c015efa,delivered,2018-06-13 02:19:56,2018-06-14 02:39:10,2018-06-14 13:55:00,2018-06-20 21:07:29,2018-07-13,7.0
3,fe2ac30768e07e362b649951cc625144,be07f06f183227b5c2b31c30fbb4f382,delivered,2017-01-16 16:41:18,2017-01-16 17:30:23,2017-01-17 11:26:52,2017-01-26 16:24:07,2017-02-22,10.0
4,460673777918e7a42a262293341ae7d5,6f352988122e277e645d36a012e66bcb,delivered,2018-02-07 22:38:41,2018-02-08 22:30:24,2018-02-09 16:56:51,2018-02-24 18:06:45,2018-03-05,17.0
...,...,...,...,...,...,...,...,...,...
99436,9c5dedf39a927c1b2549525ed64a053c,39bd1228ee8140590ac3aca26f2dfe00,delivered,2017-03-09 09:54:05,2017-03-09 09:54:05,2017-03-10 11:18:03,2017-03-17 15:08:01,2017-03-28,8.0
99437,63943bddc261676b46f01ca7ac2f7bd8,1fca14ff2861355f6e5f14306ff977a7,delivered,2018-02-06 12:58:58,2018-02-06 13:10:37,2018-02-07 23:22:42,2018-02-28 17:37:56,2018-03-02,22.0
99438,83c1379a015df1e13d02aae0204711ab,1aa71eb042121263aafbe80c1b562c9c,delivered,2017-08-27 14:46:43,2017-08-27 15:04:16,2017-08-28 20:52:26,2017-09-21 11:24:17,2017-09-27,25.0
99439,11c177c8e97725db2631073c19f07b62,b331b74b18dc79bcdf6532d51e1637c1,delivered,2018-01-08 21:28:27,2018-01-08 21:36:21,2018-01-12 15:35:03,2018-01-25 23:32:54,2018-02-15,17.0
99440,66dea50a8b16d9b4dee7af250b4be1a5,edb027a75a1449115f6b43211ae02a24,delivered,2018-03-08 20:57:30,2018-03-09 11:20:28,2018-03-09 22:11:59,2018-03-16 13:08:30,2018-04-03,8.0

In [9]:
order_items.toPandas()

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
0,8ac26cb701a7887cc7c458683408c56a,1,4ebb87ba41ca446326804d0e7f8dcc93,7a67c85e85bb2ce8582c35f2203ad736,2017-05-22 16:05:14,109.99,18.02
1,8ac2728285fd4228f35d907768b5288a,1,8b90be4893a4277a9f33c5b2348cf9c6,004c9cd9d87a3c30c522c48c4fc07416,2017-03-15 14:09:17,109.99,8.27
2,8ac2728285fd4228f35d907768b5288a,2,fa94f25a73969e3a25d52706e246dfcc,004c9cd9d87a3c30c522c48c4fc07416,2017-03-15 14:09:17,109.99,16.55
3,8ac2728285fd4228f35d907768b5288a,3,b01cedfa96d891427058852f0625e9ee,004c9cd9d87a3c30c522c48c4fc07416,2017-03-15 14:09:17,259.99,21.01
4,8ac2728285fd4228f35d907768b5288a,4,fa94f25a73969e3a25d52706e246dfcc,004c9cd9d87a3c30c522c48c4fc07416,2017-03-15 14:09:17,109.99,16.55
...,...,...,...,...,...,...,...
112645,fffc94f6ce00a00581880bf54a75a037,1,4aa6014eceb682077f9dc4bffebc05b0,b8bc237ba3788b23da09c0f1f3a3288c,2018-05-02 04:11:01,299.99,43.41
112646,fffcd46ef2263f404302a634eb57f7eb,1,32e07fd915822b0765e448c4dd74c828,f3c38ab652836d21de61fb8314b69182,2018-07-20 04:31:48,350.00,36.53
112647,fffce4705a9662cd70adb13d4a31832d,1,72a30483855e2eafc67aee5dc2560482,c3cfdc648177fdbbbb35635a37472c53,2017-10-30 17:14:25,99.90,16.95
112648,fffe18544ffabc95dfada21779c9644f,1,9c422a519119dcad7575db5af1ba540e,2b3e4a2a3ea8e01938cabda2a3e5cc79,2017-08-21 00:04:32,55.99,8.72
112649,fffe41c64501cc87c801fd61db3f6244,1,350688d9dc1e75ff97be326363655e01,f7ccf836d21b2fb1de37564105216cc1,2018-06-12 17:10:13,43.00,12.79

In [10]:
get_printSchema(customers,"customers")
get_printSchema(orders,"orders")
get_printSchema(order_items,"order_items")
get_printSchema(reviews,"reviews")
get_printSchema(products, "products")

 in the customers table
root
 |-- customer_id: string (nullable = true)
 |-- customer_unique_id: string (nullable = true)
 |-- customer_zip_code_prefix: integer (nullable = true)
 |-- customer_city: string (nullable = true)
 |-- customer_state: string (nullable = true)

 in the orders table
root
 |-- order_id: string (nullable = true)
 |-- customer_id: string (nullable = true)
 |-- order_status: string (nullable = true)
 |-- order_purchase_timestamp: timestamp (nullable = true)
 |-- order_approved_at: timestamp (nullable = true)
 |-- order_delivered_carrier_date: timestamp (nullable = true)
 |-- order_delivered_customer_date: timestamp (nullable = true)
 |-- order_estimated_delivery_date: timestamp (nullable = true)
 |-- delivery_time_days: integer (nullable = true)

 in the order_items table
root
 |-- order_id: string (nullable = true)
 |-- order_item_id: integer (nullable = true)
 |-- product_id: string (nullable = true)
 |-- seller_id: string (nullable = true)
 |-- shipping_limit_date: timestamp (nullable = true)
 |-- price: double (nullable = true)
 |-- freight_value: double (nullable = true)

 in the reviews table
root
 |-- review_id: string (nullable = true)
 |-- order_id: string (nullable = true)
 |-- review_score: integer (nullable = true)
 |-- review_comment_title: string (nullable = true)
 |-- review_comment_message: string (nullable = true)
 |-- review_creation_date: timestamp (nullable = true)
 |-- review_answer_timestamp: timestamp (nullable = true)
 |-- is_positive: boolean (nullable = true)

 in the products table
root
 |-- product_id: string (nullable = true)
 |-- product_category_name: string (nullable = true)
 |-- product_name_lenght: integer (nullable = true)
 |-- product_description_lenght: integer (nullable = true)
 |-- product_photos_qty: integer (nullable = true)
 |-- product_weight_g: integer (nullable = true)
 |-- product_length_cm: integer (nullable = true)
 |-- product_height_cm: integer (nullable = true)
 |-- product_width_cm: integer (nullable = true)

In [11]:
orders.join(
    order_items,
    "order_id",
    "left_anti"
).count()

775

## We will create 3 main Gold tables:
### -1 FACT SALES TABLE  (Grain 1row = 1 order item)

In [12]:
# Start from orders (business event)
# Order is the “main event”
# Cleaner business logic
#  One row per order (or order context)
fact_sales = orders \
    .join(order_items, "order_id", "left") \
    .join(products, "product_id", "left") \
    .join(customers, "customer_id", "left")

# you want a sales fact table at order level
# business KPIs (revenue per order, customer behavior)

## Delivery KPI

In [13]:
# delivery_delay_days
fact_sales=fact_sales.withColumn("delivery_time_days",datediff("order_delivered_customer_date", "order_purchase_timestamp")
                          )

In [14]:
fact_sales =fact_sales.withColumn(
    "total_price",
    col("price") + col("freight_value")
)

In [15]:
fact_sales.toPandas()

,customer_id,product_id,order_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,delivery_time_days,...,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state,total_price
0,4bf24904ec428325abad2791fcca1aff,2e58d459f2a674ee7b0d3d1336712acb,995392413cee61cc1fcec9807870ea8c,delivered,2017-09-04 22:24:05,2017-09-04 22:43:54,2017-09-13 17:20:04,2017-09-22 21:09:32,2017-09-27,18.0,...,1.0,460.0,18.0,13.0,13.0,c95aaeaa550e5dbd7a4386337ddba614,2846,sao paulo,SP,143.83
1,ed18b557140ff674f36cbcf73921dbbe,0d85c435fd60b277ffb9e9b0f88f927a,b39de9ed2bb8fd08a970e4517c698824,delivered,2018-03-27 09:15:17,2018-03-27 09:30:12,2018-03-27 23:52:09,2018-04-11 21:51:02,2018-04-26,15.0,...,1.0,150.0,16.0,13.0,14.0,2bdf6e9b5bcfd6c33a43ac443c0a90a4,26010,nova iguacu,RJ,121.30
2,5cf799d0ac88e1d328434a595c015efa,364e789259da982f5b7e43aaea7be615,b1a88554eb1f7f68627549e26257b583,delivered,2018-06-13 02:19:56,2018-06-14 02:39:10,2018-06-14 13:55:00,2018-06-20 21:07:29,2018-07-13,7.0,...,1.0,750.0,16.0,10.0,16.0,c5dc5c2635cadde29865e0a2d9611658,37551,pouso alegre,MG,59.46
3,be07f06f183227b5c2b31c30fbb4f382,561e48cdfacd14e7cfe67aa4ebd0caea,fe2ac30768e07e362b649951cc625144,delivered,2017-01-16 16:41:18,2017-01-16 17:30:23,2017-01-17 11:26:52,2017-01-26 16:24:07,2017-02-22,10.0,...,2.0,650.0,21.0,18.0,20.0,436951eead1cce602da9256d8c59e093,41810,salvador,BA,93.72
4,6f352988122e277e645d36a012e66bcb,b7605b5b483063d12bd90a772bff9d21,460673777918e7a42a262293341ae7d5,delivered,2018-02-07 22:38:41,2018-02-08 22:30:24,2018-02-09 16:56:51,2018-02-24 18:06:45,2018-03-05,17.0,...,2.0,550.0,40.0,7.0,50.0,5717c3a742c0df7192fd1e1016e28bf6,5187,sao paulo,SP,59.85
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
113420,1fca14ff2861355f6e5f14306ff977a7,f1d4ce8c6dd66c47bbaa8c6781c2a923,63943bddc261676b46f01ca7ac2f7bd8,delivered,2018-02-06 12:58:58,2018-02-06 13:10:37,2018-02-07 23:22:42,2018-02-28 17:37:56,2018-03-02,22.0,...,4.0,4950.0,40.0,10.0,40.0,da62f9e57a76d978d02ab5362c509660,11722,praia grande,SP,195.00
113421,1aa71eb042121263aafbe80c1b562c9c,b80910977a37536adeddd63663f916ad,83c1379a015df1e13d02aae0204711ab,delivered,2017-08-27 14:46:43,2017-08-27 15:04:16,2017-08-28 20:52:26,2017-09-21 11:24:17,2017-09-27,25.0,...,2.0,13300.0,32.0,90.0,22.0,737520a9aad80b3fbbdad19b66b37b30,45920,nova vicosa,BA,271.01
113422,b331b74b18dc79bcdf6532d51e1637c1,d1c427060a0f73f6b889a5c7c61f2ac4,11c177c8e97725db2631073c19f07b62,delivered,2018-01-08 21:28:27,2018-01-08 21:36:21,2018-01-12 15:35:03,2018-01-25 23:32:54,2018-02-15,17.0,...,1.0,6550.0,20.0,20.0,20.0,5097a5312c8b157bb7be58ae360ef43c,28685,japuiba,RJ,220.58
113423,b331b74b18dc79bcdf6532d51e1637c1,d1c427060a0f73f6b889a5c7c61f2ac4,11c177c8e97725db2631073c19f07b62,delivered,2018-01-08 21:28:27,2018-01-08 21:36:21,2018-01-12 15:35:03,2018-01-25 23:32:54,2018-02-15,17.0,...,1.0,6550.0,20.0,20.0,20.0,5097a5312c8b157bb7be58ae360ef43c,28685,japuiba,RJ,220.58
113424,edb027a75a1449115f6b43211ae02a24,006619bbed68b000c8ba3f8725d5409e,66dea50a8b16d9b4dee7af250b4be1a5,delivered,2018-03-08 20:57:30,2018-03-09 11:20:28,2018-03-09 22:11:59,2018-03-16 13:08:30,2018-04-03,8.0,...,1.0,150.0,16.0,7.0,15.0,60350aa974b26ff12caad89e55993bd6,83750,lapa,PR,86.86

In [16]:
fact_sales.printSchema()

root
 |-- customer_id: string (nullable = true)
 |-- product_id: string (nullable = true)
 |-- order_id: string (nullable = true)
 |-- order_status: string (nullable = true)
 |-- order_purchase_timestamp: timestamp (nullable = true)
 |-- order_approved_at: timestamp (nullable = true)
 |-- order_delivered_carrier_date: timestamp (nullable = true)
 |-- order_delivered_customer_date: timestamp (nullable = true)
 |-- order_estimated_delivery_date: timestamp (nullable = true)
 |-- delivery_time_days: integer (nullable = true)
 |-- order_item_id: integer (nullable = true)
 |-- seller_id: string (nullable = true)
 |-- shipping_limit_date: timestamp (nullable = true)
 |-- price: double (nullable = true)
 |-- freight_value: double (nullable = true)
 |-- product_category_name: string (nullable = true)
 |-- product_name_lenght: integer (nullable = true)
 |-- product_description_lenght: integer (nullable = true)
 |-- product_photos_qty: integer (nullable = true)
 |-- product_weight_g: integer (nullable = true)
 |-- product_length_cm: integer (nullable = true)
 |-- product_height_cm: integer (nullable = true)
 |-- product_width_cm: integer (nullable = true)
 |-- customer_unique_id: string (nullable = true)
 |-- customer_zip_code_prefix: integer (nullable = true)
 |-- customer_city: string (nullable = true)
 |-- customer_state: string (nullable = true)
 |-- total_price: double (nullable = true)

# DIM CUSTOMER

In [17]:
dim_customers = customers.select(
    "customer_id",
    "customer_unique_id",
    "customer_city",
    "customer_state",
    "customer_zip_code_prefix"
)

# DIM PRODUCT

In [18]:
dim_products = products.select(
    "product_id",
    "product_category_name",
    "product_weight_g",
    "product_length_cm",
    "product_height_cm",
    "product_width_cm",
    "product_photos_qty"
)                              ##.dropDuplicates(["product_id"])

## DIM REVIEW

In [19]:
dim_reviews = reviews.select(
    "review_id",
    "order_id",
    "review_score",
    "is_positive",
    "review_creation_date"
)

# DIM TIME

In [20]:
dim_time = orders.select(
    "order_id",
    to_date("order_purchase_timestamp").alias("order_date"),
    year("order_purchase_timestamp").alias("year"),
    month("order_purchase_timestamp").alias("month"),
    dayofmonth("order_purchase_timestamp").alias("day")
)

 #               dim_customers
                                  |
# dim_products —  fact_sales  — dim_reviews
                                  |
 #                              dim_time

# ********** STORE IN GOLD LAYER ************

In [21]:
fact_sales.write.mode("overwrite").parquet("hdfs://namenode:8020/user/root/goldl/fact_sales/")
dim_customers.write.mode("overwrite").parquet("hdfs://namenode:8020/user/root/goldl/dim_customers/")
dim_products.write.mode("overwrite").parquet("hdfs://namenode:8020/user/root/goldl/dim_products/")
dim_reviews.write.mode("overwrite").parquet("hdfs://namenode:8020/user/root/goldl/dim_reviews/")
dim_time.write.mode("overwrite").parquet("hdfs://namenode:8020/user/root/goldl/dim_time/")

### in hive we created our structure

#### /user/root/goldl/
##    ├── fact_sales/
##    ├── dim_customers/
##    ├── dim_products/
##    ├── dim_reviews/
##    └── dim_time/

## Agg

## 2. CUSTOMER ANALYTICS TABLE
### Purpose:
- customer behavior
- segmentation
-  activity

In [ ]:
##1= Types of Gold layer * * final business outputs
# -- Star schema Gold (traditional BI)  (blueprint of warehouse)
# --  fact tables + dimension tables
# ** used in warehouses (Snowflake, BigQuery)

#2 = Aggregated Gold tables
# Used for dashboards
# -3 = Flat tables (denormalized)
# fact_sales (everything joined together)

#  Fast for ML
#  Simple queries

In [22]:
# customer_gold = orders \
#     .join(customers, "customer_id") \
#     .groupBy("customer_id", "customer_city", "customer_state") \
#     .agg(
#         _sum("delivery_time_days").alias("total_delivery_days")
#     )

# REVIEW ANALYTICS TABLE
#### Purpose:

--- satisfaction analysis

--- sentiment proxy

In [24]:
# review_gold = reviews.groupby("order_id", "is_positive").agg(_sum("review_score").alias("total_score"))

# 4. PRODUCT PERFORMANCE TABLE
### Purpose:
-- best products

-- category analysis

In [25]:
# product_gold = order_items \
#     .join(products, "product_id") \
#     .groupBy("product_id", "product_category_name") \
#     .agg(
#         _sum("price").alias("total_revenue"),
#         _sum("freight_value").alias("total_freight")
#     )

In [ ]:
## so now gold layer have Gold Layer:
# fact_sales        >>  main table
# customer_gold    >> behavior
# review_gold       >>  satisfaction
# product_gold     >>  performance

In [18]:
# ## you can use also the next but this  More granular(each product per order)
# fact_order_items  = order_items \
#     .join(orders, "order_id", "left") \
#     .join(customers, "customer_id", "left") \
#     .join(products, "product_id", "left")
# # you need line-level analytics
# # product-level revenue per item
# # very detailed reporting

In [17]:
# fact_sales.toPandas()

,customer_id,product_id,order_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,order_item_id,...,product_weight_g,product_length_cm,product_height_cm,product_width_cm,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state,delivery_time_days,total_price
0,4bf24904ec428325abad2791fcca1aff,2e58d459f2a674ee7b0d3d1336712acb,995392413cee61cc1fcec9807870ea8c,delivered,2017-09-04 22:24:05,2017-09-04 22:43:54,2017-09-13 17:20:04,2017-09-22 21:09:32,2017-09-27,1.0,...,460.0,18.0,13.0,13.0,c95aaeaa550e5dbd7a4386337ddba614,2846,sao paulo,SP,18.0,143.83
1,ed18b557140ff674f36cbcf73921dbbe,0d85c435fd60b277ffb9e9b0f88f927a,b39de9ed2bb8fd08a970e4517c698824,delivered,2018-03-27 09:15:17,2018-03-27 09:30:12,2018-03-27 23:52:09,2018-04-11 21:51:02,2018-04-26,1.0,...,150.0,16.0,13.0,14.0,2bdf6e9b5bcfd6c33a43ac443c0a90a4,26010,nova iguacu,RJ,15.0,121.30
2,5cf799d0ac88e1d328434a595c015efa,364e789259da982f5b7e43aaea7be615,b1a88554eb1f7f68627549e26257b583,delivered,2018-06-13 02:19:56,2018-06-14 02:39:10,2018-06-14 13:55:00,2018-06-20 21:07:29,2018-07-13,1.0,...,750.0,16.0,10.0,16.0,c5dc5c2635cadde29865e0a2d9611658,37551,pouso alegre,MG,7.0,59.46
3,be07f06f183227b5c2b31c30fbb4f382,561e48cdfacd14e7cfe67aa4ebd0caea,fe2ac30768e07e362b649951cc625144,delivered,2017-01-16 16:41:18,2017-01-16 17:30:23,2017-01-17 11:26:52,2017-01-26 16:24:07,2017-02-22,1.0,...,650.0,21.0,18.0,20.0,436951eead1cce602da9256d8c59e093,41810,salvador,BA,10.0,93.72
4,6f352988122e277e645d36a012e66bcb,b7605b5b483063d12bd90a772bff9d21,460673777918e7a42a262293341ae7d5,delivered,2018-02-07 22:38:41,2018-02-08 22:30:24,2018-02-09 16:56:51,2018-02-24 18:06:45,2018-03-05,1.0,...,550.0,40.0,7.0,50.0,5717c3a742c0df7192fd1e1016e28bf6,5187,sao paulo,SP,17.0,59.85
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
113420,1fca14ff2861355f6e5f14306ff977a7,f1d4ce8c6dd66c47bbaa8c6781c2a923,63943bddc261676b46f01ca7ac2f7bd8,delivered,2018-02-06 12:58:58,2018-02-06 13:10:37,2018-02-07 23:22:42,2018-02-28 17:37:56,2018-03-02,1.0,...,4950.0,40.0,10.0,40.0,da62f9e57a76d978d02ab5362c509660,11722,praia grande,SP,22.0,195.00
113421,1aa71eb042121263aafbe80c1b562c9c,b80910977a37536adeddd63663f916ad,83c1379a015df1e13d02aae0204711ab,delivered,2017-08-27 14:46:43,2017-08-27 15:04:16,2017-08-28 20:52:26,2017-09-21 11:24:17,2017-09-27,1.0,...,13300.0,32.0,90.0,22.0,737520a9aad80b3fbbdad19b66b37b30,45920,nova vicosa,BA,25.0,271.01
113422,b331b74b18dc79bcdf6532d51e1637c1,d1c427060a0f73f6b889a5c7c61f2ac4,11c177c8e97725db2631073c19f07b62,delivered,2018-01-08 21:28:27,2018-01-08 21:36:21,2018-01-12 15:35:03,2018-01-25 23:32:54,2018-02-15,2.0,...,6550.0,20.0,20.0,20.0,5097a5312c8b157bb7be58ae360ef43c,28685,japuiba,RJ,17.0,220.58
113423,b331b74b18dc79bcdf6532d51e1637c1,d1c427060a0f73f6b889a5c7c61f2ac4,11c177c8e97725db2631073c19f07b62,delivered,2018-01-08 21:28:27,2018-01-08 21:36:21,2018-01-12 15:35:03,2018-01-25 23:32:54,2018-02-15,1.0,...,6550.0,20.0,20.0,20.0,5097a5312c8b157bb7be58ae360ef43c,28685,japuiba,RJ,17.0,220.58
113424,edb027a75a1449115f6b43211ae02a24,006619bbed68b000c8ba3f8725d5409e,66dea50a8b16d9b4dee7af250b4be1a5,delivered,2018-03-08 20:57:30,2018-03-09 11:20:28,2018-03-09 22:11:59,2018-03-16 13:08:30,2018-04-03,1.0,...,150.0,16.0,7.0,15.0,60350aa974b26ff12caad89e55993bd6,83750,lapa,PR,8.0,86.86